### ISSUE TITLE
Trigger matching

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/TTAnalysis#5]

**Comment by blinkseb** [comment]
See https://github.com/swertz/TTAnalysis/compare/secondRound...blinkseb:trigger

**Comment by blinkseb** [comment]
It seems to work quite well, at least on MC. If there's a trigger fired, I always find a match between the offline lepton and the online one.

Also, PDG id of `hlt_objects` is not consistent. It's always `0` for electrons, while it's correct for muons. That's why I did not use the information for the matching.

**Comment by swertz** [comment]
Great :) What values of DeltaR/DeltaPt did you use for the test?

**Comment by blinkseb** [comment]
I left the default values, so basically no cuts applied. From my test, deltaR is always < 10^-4 while delta Pt / Pt is < 1%

**Comment by swertz** [comment]
Closed by #11
